TOOL-1105 Updated caching for NuGet restore step.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,98 +1,145 @@
-format_version: 1.3.0
+format_version: 9
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
 app:
   envs:
-  - STEP_VERSION: 1.0.7
-
-  - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-apps-xamarin-ios.git
-  - BITRISE_PROJECT_PATH: CreditCardValidator.iOS.sln
+    - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-apps-xamarin-ios.git
+    - BITRISE_PROJECT_PATH: CreditCardValidator.iOS.sln
 
 workflows:
   # ----------------------------------------------------------------
   # --- workflow to Step Test
   test:
     before_run:
-    - audit-this-step
+      - audit-this-step
     steps:
-    - go-list:
-    - golint:
-    - errcheck:
-    - go-test:
+      - go-list:
+      - golint:
+      - errcheck:
+      - go-test:
+    after_run:
+      - _common
+      - _test_local_cache
+      - _test_global_cache
+      - _test_no_cache
+
+  _common:
+    steps:
     - script:
+        title: Clear tmp directory
         inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-            set -v
-            rm -rf ./_tmp
+          - content: |-
+              #!/bin/bash
+              set -e
+              set -v
+              rm -rf ./_tmp
     - change-workdir:
         title: Switch working dir to ./_tmp dir
         inputs:
-        - path: ./_tmp
-        - is_create_path: true
+          - path: ./_tmp
+          - is_create_path: true
     - script:
-        title: Clone sapmle app
+        title: Clone sample app
         inputs:
-        - content: git clone $SAMPLE_APP_URL .
-    - path::./:
-        title: Step Test
-        run_if: true
-        inputs:
-         - nuget_version: "latest"
-    - script:
-        title: Print cache paths
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -e
-            echo $BITRISE_CACHE_INCLUDE_PATHS
+          - content: git clone $SAMPLE_APP_URL .
 
-  # ----------------------------------------------------------------
-  # --- Utility workflows
-  godeps-update:
-    title: Godeps update
-    description: |
-      Used for updating bitrise dependencies with godep
+  _clear_cache:
     steps:
     - script:
-        title: Dependency update
+        title: Clear cache
         inputs:
-        - content: |
-            #!/bin/bash
-            set -ex
-            go get -u -v github.com/tools/godep
+          - content: |-
+              #!/bin/bash
+              envman add --key "BITRISE_CACHE_INCLUDE_PATHS" --value ""
 
-            rm -rf ./Godeps
-            rm -rf ./vendor
-
-            go get -t -d ./...
-            godep save ./...
-
-  # ----------------------------------------------------------------
-  # --- workflow to create Release version
-  create-release:
+  _test_local_cache:
+    before_run:
+      - _clear_cache
     steps:
-    - script:
-        title:
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -ex
-            go get -u github.com/bitrise-tools/releaseman
-            export CI=true
-            releaseman create --version "$STEP_VERSION"
+      - path::./:
+          title: Step Test with local caching
+          run_if: true
+          inputs:
+            - nuget_version: "latest"
+            - allow_caching: "local"
+      - script:
+          title: Print and validate local cache paths
+          inputs:
+            - content: |
+                #!/bin/bash
+                set -e
+                echo "Exported local cache dir is $BITRISE_CACHE_INCLUDE_PATHS"
+                DIR="$(pwd)/packages"
+
+                if [ $BITRISE_CACHE_INCLUDE_PATHS == $DIR ]; then
+                    echo "Local cache dir found correctly"
+                else
+                    echo "Did not found local cache dir correctly"
+                    exit 1
+                fi
+
+  _test_global_cache:
+    before_run:
+      - _clear_cache
+    steps:
+      - path::./:
+          title: Step Test with global caching
+          run_if: true
+          inputs:
+            - nuget_version: "latest"
+            - allow_caching: "global"
+      - script:
+          title: Print and validate global cache paths
+          inputs:
+            - content: |
+                #!/bin/bash
+                set -e
+                echo "Exported global cache dir is $BITRISE_CACHE_INCLUDE_PATHS"
+                DIR=~/.nuget/packages
+                if [ $BITRISE_CACHE_INCLUDE_PATHS == $DIR ]; then
+                  echo "Global cache dir found correctly"
+                elif [ $BITRISE_CACHE_INCLUDE_PATHS == $NUGET_PACKAGES ]; then
+                  echo "Global cache dir found correctly from env variable"
+                else
+                  echo "Did not found global cache dir correctly"
+                  exit 1
+                fi
+
+  _test_no_cache:
+    before_run:
+      - _clear_cache
+    steps:
+      - path::./:
+          title: Step Test with no caching
+          run_if: true
+          inputs:
+            - nuget_version: "latest"
+            - allow_caching: "none"
+      - script:
+          title: Print and validate cache paths
+          inputs:
+            - content: |
+                #!/bin/bash
+                set -e
+                echo "Exported global cache dir is $BITRISE_CACHE_INCLUDE_PATHS"
+                DIR=~/.nuget/packages
+                if [ -z $BITRISE_CACHE_INCLUDE_PATHS ]; then
+                  echo "Cache paths are empty"
+                else
+                  echo "Cache paths are not empty, but they should"
+                  exit 1
+                fi
 
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
   audit-this-step:
     steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            stepman audit --step-yml ./step.yml
+      - script:
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -ex
+                stepman audit --step-yml ./step.yml
 
   share-this-step:
     envs:
@@ -123,13 +170,13 @@ workflows:
       Once it finishes the only thing left is to actually create a Pull Request,
       the way described in the guide printed at the end of the process.
     before_run:
-    - audit-this-step
+      - audit-this-step
     steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
-            bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
-            bitrise share finish
+      - script:
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -ex
+                bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
+                bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
+                bitrise share finish
